on: [push, pull_request]
name: Main
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test -v ./...
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23.x
      - name: Checkout
        uses: actions/checkout@v4.2.2
        #with:
        #token: ${{ secrets.GH_PAT }}
      - name: Build Release
        run: make -j4 build_all
      - name: Publish to Github
        uses: softprops/action-gh-release@v2
        with:
          #token: ${{ secrets.GH_PAT }}
          files: ./bin/*
