on: [push, pull_request]
name: Main
jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - name: Check Code
        run: |
          go mod verify
          go vet ./...
      - name: Tests
        run: go test -v ./...
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify
        run: go mod verify
      - name: Build Release
        run: make -j4 build_all
      - name: Publish to Github
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/*
          generate_release_notes: "true"
