name: Publish release
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  publish-release:
   if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_commit.message, 'refs/tags/') }}
   name: "Publish release"
   runs-on: ubuntu-latest
   permissions:
     contents: write
   steps:
     - uses: actions/setup-go@v3
       with:
         go-version: 1.23.x
     - name: Checkout
       uses: actions/checkout@v4.2.2
       #with:
         #token: ${{ secrets.GH_PAT }}
     - name: Build Release
       run: make -j4 build_all
     - name: Publish to Github
       uses: softprops/action-gh-release@v2
       with:
         #token: ${{ secrets.GH_PAT }}
         files: ./bin/*
